### ISSUE TITLE
When installing controls from npm, Imagefilter doesn't get included in the node module file structure

### ISSUE THREAD

**Issue by nejurgis** [BabylonJS/Controls#29]
Everything else besides ImageFilter gets installed

**Comment by sebavan** [comment]
ohhhhh so weird let me try it now.

**Comment by sebavan** [comment]
Actually are you using the latest preview ? 

npm install @babylonjs/controls@preview

cause I can see it in there:

![image](https://user-images.githubusercontent.com/16655165/85185449-3e660a00-b294-11ea-8ac0-14b19de4b4c3.png)

I am closing the issue for now as it looks like you might be using an older version. I ll reopen if the issue is somewhere else.
